

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT UNIQUE,
    full_name TEXT NOT NULL,
    short_name TEXT
);

INSERT OR REPLACE INTO user VALUES (42, "a0e0b904-3a6f-4877-b9b2-40c4c5ac40c5", "Marc SIBERT", "Marcus")
